apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # generateName: retry-on-error-
  name: memory-leak
spec:
  entrypoint: leak-container
  templates:
    - name: leak-container
      retryStrategy:
        limit: "5"
        retryPolicy: "Always"
      container:
        image: ghcr.io/atlanhq/go-leak:latest
        command: ["/bin/sh", "-c", "./main"]
