apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # generateName: retry-on-error-
  name: retry-on-error
spec:
  entrypoint: error-container
  templates:
  - name: error-container
    retryStrategy:
      limit: "5"
      retryPolicy: "Always"
    container:
      image: python
      command: ["python", "-c"]
      # fail with a 80% probability
      args: ["import random; import sys; exit_code = random.choice(range(0, 5)); sys.exit(exit_code)"]